contas/apps/gestor/urls.py
from django.urls import path

app_name  = 'gestor'

from . import views

urlpatterns = [
    path('adicionar-conta/', views.adicionar_conta, name='adicionar_conta'),
    path('contas-pagar/', views.lista_contas_pagar, name='lista_contas_pagar'),
    path('contas-receber/', views.lista_contas_receber, name='lista_contas_receber'),
    path('pessoas/', views.lista_adicionar_pessoa, name='lista_adicionar_pessoa'),
    path('editar-pessoa/<int:id_pessoa>/', views.editar_pessoa, name='editar_pessoa'),
    path('deletar-pessoa/<int:id_pessoa>/', views.deletar_pessoa, name='deletar_pessoa'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('', views.home, name='home'),
]

contas/contas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestor.urls', namespace='gestor')),
    ]

contas/apps/gestor/models.py
from django.db import models

# Create your models here.

class Pessoa(models.Model):
    nome = models.CharField(verbose_name='Nome', max_length= 200)
    nascimento = models.DateField(verbose_name='Nascimento')
    cpf = models.CharField(verbose_name='CPF', max_length= 14) #000.000.000-00

    def __str__(self):
        return self.nome

class Conta(models.Model):
    TIPO_CONTA_CHOICE = (
        ('RB', 'A receber'),
        ('PG', 'A pagar'),
    )
    pessoa = models.ForeignKey(Pessoa, verbose_name='Pessoa', on_delete=models.CASCADE)
    tipo_conta = models.CharField(verbose_name='Tipo de Conta', max_length=2, choices=TIPO_CONTA_CHOICE)
    vencimento = models.DateField(verbose_name='vencimento')
    valor = models.DecimalField(verbose_name='valor R$', max_digits=19, decimal_places=2)

    def __str__(self):
        return "Nome: {} - Valor R$: {}".format(self.pessoa.nome, self.valor)

contas/apps/gestor/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Conta, Pessoa

class ContaForm(forms.ModelForm):
    
    class Meta:
        model = Conta
        fields = '__all__' # ['pessoa', 'tipo_conta', 'vencimento', 'valor']

    class PessoaForm(forms.ModelForm):

        class Meta:
            model = Pessoa
            fields = '__all__'  

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'passoword']

contas/apps/gestor/views.py
from django.shortcuts import render, redirect
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from .models import Conta, Pessoa
from .forms import ContaForm, PessoaForm, UserForm

# Create your views here.

def user_login(request):
    if request.method =='POST':
        username = request.POST.get ('username')
        password = request.POST.get ('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('gestor:home')
        else:
            messages.error(request, 'usuário ou senha inválida.')
        return render(request, 'user_login.html', {})


@login_required(login_url='/login/')
def user_logout(request):
    logout(request)
    return redirect('gestor: user_login')

def add_user(request)
    if request.method=='POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.set_password(f.password)
            f.save()
            return redirect('gestor:user_login')
        form = UserForm()
        return render(request, 'add_user.html', {'form':form})    


@login_required(login_url='/login/')
def home(request):
    lista_contas = Conta.objects.all() #SELECT * FROM Conta, #Query Set
    return render(request, 'base.html', {'lista_contas': lista_contas})

@login_required(login_url='/login/')
def adicionar_conta(request):
    if request.method == 'POST':
        form = ContaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('gestor:home')
    form = ContaForm() 
    return render(request, 'adicionar_conta.html', {'form': form})

@login_required(login_url='/login/')
def lista_contas_pagar(request):
    contas_pagar = Conta.objects.filter(tipo_conta='PG')
    total = contas_pagar.aggregate(Sum('valor'))['valor__sum']
    return render(request, 'lista_contas_pagar.html', {'contas_pagar': contas_pagar, 'total': total})

@login_required(login_url='/login/')
def lista_contas_receber(request):
    contas_receber = Conta.objects.filter(tipo_conta='RB')
    total = contas_receber.aggregate(Sum('valor'))['valor__sum']
    return render(request, 'lista_contas_receber.html', {'contas_receber': contas_receber, 'total'})

@login_required(login_url='/login/')
def lista_adicionar_pessoa(request):
    pessoas = Pessoa.objects.all()
    if request.method =='POST':
        form = PessoaForm(request.POST)
         form.save()
         return redirect('gestor:lista_pessoas')
    form = PessoaForm()
    return render(request, 'lista_adicionar_pessoa.html', {'form': form, 'pessoas': pessoas})

@login_required(login_url='/login/')
def editar_pessoa(request, id_pessoa):
    pessoa = Pessoa.objects.get(id=id_pessoa)
    if request.method == 'POST':
        form = PessoaForm(request.POST, instance=pessoa)
        if form.is_valid()
        form.save()
        return redirect('gestor: lista_adicionar_pessoa')
    form = PessoaForm(instance=pessoa)
    return render(request, 'lista_adicionar_pessoa.html', {'form': form,'pessoas': pessoas})

@login_required(login_url='/login/')
def deletar_pessoa(request, id_pessoa):
    Pessoa.objects.get(id=id_pessoa).delete()
    return redirect('gestor:lista_adicionar_pessoa')    



contas/templates/add_user.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block titulo %}

Criar Usuário | {{ block.super }}

{% endblock titulo %}

{% block corpo %}

    <h1>Prencha o formulário abaixo</h1>
    <form action="" method="post" autocomplete="off">
    {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.first_name.id_for_label}}">{{form.first_name.label}}</label>
            {% render_field form.first_name class="form-control" autofocus="autofocus"%}           
        </div>
        <div class="form-group">
            <label for="{{ form.last_name.id_for_label}}">{{form.last_name.label}}</label>
            {% render_field form.last_name class="form-control" autofocus %}
        </div>    
        <div class="form-group">
                <label for="{{ form.user_name.id_for_label}}">{{form.user_name.label}}</label>
                {% render_field form.user_name class="form-control" autofocus %}           
        </div>
        <div class="form-group">
            <label for="{{ form.password.id_for_label}}">{{form.password.label}}</label>
            {% render_field form.password class="form-control" autofocus %}           
        </div>
                
        <button type="submit" class="btn btn-primary">Criar</button>
        <a href="{% url 'gestor: add_user' %}" class="btn btn-info"> Cancelar</a>></a>
    </form>

{% endblock corpo %}

contas/templates/adicionar_conta.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block titulo %}
    
    Adicionar Nova Conta

{% endblock titulo %}

{% block corpo %}
    <h1>Adicionar uma Nova Conta</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.pessoa.id_for_label}}">{{form.pessoa.label}}</label>
            {% render_field form.pessoa class="form-control" %}
        </div>
        <div class="form-group">
            <label for="{{ form.tipo_conta.id_for_label}}">{{form.tipo_conta.label}}</label>
            {% render_field form.tipo_conta class="form-control" %}
        </div>

        <div class="form-group">
            <label for="{{ form.vencimento.id_for_label}}">{{form.vencimento.label}}</label>
            {% render_field form.vencimento class="form-control" %}
        </div>
        <div class="form-group">
            <label for="{{ form.valor.id_for_label}}">{{form.valor.label}}</label>
            {% render_field form.valor class="form-control" %}
        </div>
        
        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>
{% endblock corpo %}

contas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>{% block titulo %} Controle de contas a Pagar e a Receber {% endblock titulo %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Contas</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'gestor:lista_contas_pagar' %}">Contas a Pagar</a>
          <a class="dropdown-item" href="{% url 'gestor:lista_contas_receber' %}">Contas a Receber</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'gestor:lista_adicionar_pessoa' %}">Adicionar pessoa</a>
          <a class="dropdown-item" href="{% url 'gestor:adicionar_conta' %}">Adicionar Nova Conta</a>
          <div class="dropdown-divider"></div>
          {% if user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'gestor:user_logout' %}">Sair</a>
          {% endif %}
      </div>
      </li>
  </ul>
  <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Busca" aria-label="Buscar">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    
<div class="container">
    <div class="rows">
        <div class="col-12">

        {% block corpo %}
            <h1>Lista de contas a pagar e receber</h1>
        </div>
    </div>
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Credor/Devedor</th>
            <th scope="col">Tipo de Conta</th>
            <th scope="col">Vencimento</th>
            <th scope="col">Valor R$</th>
        </tr>
    </thead>
    <tbody>
         {% for conta in lista_contas %} 
            <tr>
                <th scope="row">{{ conta.id}}</th>
                <td>{{ conta.pessoa.nome}}</td>
                <td>{{ conta.get_tipo_conta_display}}</td>
                <td>{{ conta.vencimento}}</td>
                <td>{{ conta.valor}}</td>
            </tr>    
        {% endfor %}
    </tbody>
</table>
{% endblock corpo %}

<script src="{% static 'js/jquery.js' %}"> </script>
<script src="{% static 'js/bootstrap.js' %}"> </script>
</body>
</html>

contas/templates/lista_adicionar_pessoa.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block titulo %}

Lista/Cadastra Pessoas | {{ block.super }}

{% endblock titulo %}

{% block corpo %}

<h1>Adicionar nova Pessoa</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.nome.id_for_label}}">{{form.pessoa.label}}</label>
            {% render_field form.nome class="form-control" %}
        </div>
        <div class="form-group">
            <label for="{{ form.nascimento}}">{{form.nascimento}}</label>
            {% render_field form.nascimento class="form-control" %}
        </div>

        <div class="form-group">
            <label for="{{ form.cpf.id_for_label}}">{{form.cpf.label}}</label>
            {% render_field form.cpf class="form-control" %}
        </div>
                
        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>

    <br>

<h1>Lista de Credores/Devedores</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nome</th>
            <th scope="col">Nascimento</th>
            <th scope="col">CPF</th>
            <th scope="col">Ações</th>
            <th </th>
        </tr>
    </thead>
    <tbody>
        {% for pessoas in pessoas %}
        <tr>
            <th scope="row">{{ pessoa.id}}</th>
            <td>{{ pessoa.nome}}</td>
            <td>{{ pessoa.nascimento}}</td>
            <td>{{ pessoa.cpf}}</td>
            <td colspan="2">
                <a href="{% url 'gestor:editar_pessoa' pessoa.id %}" class="btn btn-primary bnt-sm">Editar</a><a href="" class="btn btn-danger bnt-sm">Deletar</a>
                <a href="{% url 'gestor:deletar_pessoa' pessoa.id %}" class="btn btn-primary bnt-sm">Editar</a><a href="" class="btn btn-danger bnt-sm">Deletar</a>
        </td>
        </tr>
        {% endfor %}
        
    </tbody>
</table>
<span> Total de Contas a Receber: R$ {{ total }}</span>
{% endblock corpo %}

contas/templates/lista_contas_pagar.html
{% extends 'base.html' %}

{% block titulo %}
    
    Lista de Contas a Pagar | {{ block.super }}

{% endblock titulo %}

 {% block corpo %}
            
    <h1>Contas a Pagar</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Código</th>
                <th scope="col">Credor</th>
                <th scope="col">Tipo de Conta</th>
                <th scope="col">Vencimento</th>
                <th scope="col">Valor R$</th>
            </tr>
        </thead>
        <tbody>
            {% for conta in contas_pagar %} 
                <tr>
                    <th scope="row">{{ conta.id}}</th>
                    <td>{{ conta.pessoa.nome}}</td>
                    <td>{{ conta.get_tipo_conta_display}}</td>
                    <td>{{ conta.vencimento}}</td>
                    <td>{{ conta.valor}}</td>
                </tr>    
            {% endfor %}
                    </tbody>
    </table>
    <span> Total de Contas a Pagar: R$ {{ total }}</span>
{% endblock corpo %}
   

contas/templates/lista_contas_receber.html
{% extends 'base.html' %}

{% block titulo %}

Lista de Contas a Receber | {{ block.super }}

{% endblock titulo %}

{% block corpo %}

<h1>Contas a Receber</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Devedor</th>
            <th scope="col">Tipo de Conta</th>
            <th scope="col">Vencimento</th>
            <th scope="col">Valor R$</th>
        </tr>
    </thead>
    <tbody>
        {% for conta in contas_receber %}
        <tr>
            <th scope="row">{{ conta.id}}</th>
            <td>{{ conta.pessoa.nome}}</td>
            <td>{{ conta.get_tipo_conta_display}}</td>
            <td>{{ conta.vencimento}}</td>
            <td>{{ conta.valor}}</td>
        </tr>
        {% endfor %}
        
    </tbody>
</table>
<span> Total de Contas a Receber: R$ {{ total }}</span>
{% endblock corpo %}

contas/templates/user_login.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block titulo %}

Login | {{ block.super }}

{% endblock titulo %}

{% block corpo %}

<h1>Informe usuário e senha</h1>
    <form action="" method="post" autocomplete="off">
    {% csrf_token %}
        <div class="form-group">
            <label for="">Nome de usuário </label>
            <input type="text" class="form-control" name="username" id="id_username" autofocus>
        </div>
        <div class="form-group">
            <label for="id_passoword">Senha</label>
            <input type="passoword" class="form-control" name="passoword" id="id_passoword">

        </div>
                
        <button type="submit" class="btn btn-primary">Entrar</button>
        <a href="{% url 'gestor: add_user' %}" class="btn btn-info"> Criar usuário</a>></a>
    </form>

{% endblock corpo %}